### ISSUE TITLE
Achievement 103 is not awarded consistently

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#1]
`Type:` Possible oversight

`Description:`Achievement 103 is not awarded when Burd interrupts the player having sex with Dran after the horse scene in Toris' basement.  Every other interruption by Burd in another sex scene has an associated achievement.

`Version:` v1.1.2.0 only

`Steps to repro:` Have sex with Dran at night while Burd is looking for the PC.

`Cause:` None

`Suggested fix:` Add a `SetAchievementDone()` call to the scene script.

**Comment by brewmasterhal** [comment]
Please confirm: SetAchievementDone() call added to scene in v1.2.x ?

**Comment by DogmaMods** [comment]
Yes.
