### ISSUE TITLE
Sound bug causes permanent silence

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#10]
`Type:` Sound bug

`Description:` After taking the Lunar Nirnroot, a voiced line plays and is cut off.  Following this, many of the sex sounds cease to play.

`Version:` All versions

`Steps to repro:` Take the Lunar Nirnroot and escape the cave, then continue playing

`Cause:` Unknown

`Suggested fix:` Perhaps simply removing that particular line would be easiest --  it plays so quickly that it's hard to even read it in time

**Comment by DogmaMods** [comment]
Deleted the phrase. 1.2.0.6
