### ISSUE TITLE
Skip script error

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#25]
`Type:` Script bug

`Description:` The skip script fails to show the prompts about having sex with the dock worker in the alley

`Version:` v1.2

`Steps to repro:` Start the skip script, then select the option `Разделись` when the prompt `Когда рабочий захотел узнать, сколько получит за свое молчание, Вы...` is displayed

`Cause:` Unknown

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.5
