### ISSUE TITLE
Dangling quests aliases from v1.1

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#3]
`Type:` Inaccessible content

`Description:` Interacting with the bed or any other object in Grunvald's suite does nothing.

`Version:` v1.0.0.8 only

`Steps to repro:` Rent the suite from Grunvald, enter and attempt to use the bed to go to sleep.

`Cause:` Quest aliases referencing content that was added in v1.1 were left dangling when the records the aliases point to were deleted during the creation of v1.0.0.8 - specifically the aliases `brottvar` and `hp_sw_brot_t_01_Dream`.  When the game engine attempts to execute the `OnActivate()` block of any of the activators within the suite, the dangling references cause the script to crash and terminate.

`Suggested fix:` Remove the dangling aliases and re-compile the quest and scripts - alternatively, just wait for v1.2

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.5
