### ISSUE TITLE
Mysterious mushroom object is added to PC inventory upon meeting Hidara

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#30]
`Type:` Oversight?

`Description:` A piece of armor with the name "mushroom", the in-inventory appearance of a dragon priest mask, and the equipped appearance of a held giant red-capped mushroom is added to the player's inventory during the scene when Hidara is met.  This item appears to be intended to be added to the inventory later, when the player picks up the mushroom to bring back.

`Version:` v1.2

`Steps to repro:` Enter Hidara's house, check inventory upon leaving.

`Cause:` Unknown

**Comment by brewmasterhal** [comment]
The item remains in inventory after bringing the gibbering mushroom to Hidara.

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.6
