### ISSUE TITLE
Appears to be no way to cancel renting the mill room from Varnius

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#35]
`Type:` Oversight

`Description:` If you enter the negotiation minigame with Varnius to rent his room in the mill on a permanent basis, there is no way to cancel out.  Offering him an amount that he does not accept closes the window, but it then re-opens after his dialog about not accepting the offer.  This causes a situation where the player is permanently locked in this minigame if they are unable to offer enough to buy the room.

`Version:` v1.2

`Steps to repro:` Ask Varnius about renting his spare room permanently, with less than about 10,000 gold in inventory.

`Cause:` Unknown

**Comment by DogmaMods** [comment]
It is arranged in such a way that it can be offered three times, and if it fails, then on that day it will no longer bargain. But I'll probably redo it so I can undo it.

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.7
