### ISSUE TITLE
Interactable object bugs

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#37]
`Type:` Oversight

`Description:` Certain interactable objects have confusing labels or conditions.  The little table in the lumber mill that Lodvar tells you to use to get dressed for work is labeled as "empty" when targeted in-game.  The trap door leading to the attic in the Lylvieve house is a normal activatable door but has no cell attached to the record, meaning that the player can open and close it but nothing happens.

`Version:` v1.2

`Steps to repro:` None

`Cause:` Unknown

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.7
