### ISSUE TITLE
After helping Faida with training on Sundas, the next morning is Sundas

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#40]
`Type:` Script bug

`Description:` The scenes where the PC trains Faida start on Sundas night, after 20:00, but the next morning is still Sundas.  Also, the dialog indicates that when the scene ends it is almost dawn, but in reality it is only about 02:30.

`Version:` v1.2.0.5

`Steps to repro:` Go through the Faida training scenes, then check the date/time

`Cause:` Unknown

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.7
