### ISSUE TITLE
Non-player-owned Deathbells present in palace suite

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#5]
`Type:` Oversight

`Description:` There are Deathbell flowers on the floor in the guest suite in the Blue Palace that are marked as owned and are thus stolen if picked up

`Version:` Versions after v1.0

`Steps to repro:` Enter the cell and look on the floor near the Dwemer chest

`Cause:` I would guess that part of the cell was copied from a vanilla cell

`Suggested fix:` Delete the items or remove ownership

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.6
