### ISSUE TITLE
Autosave is blocked

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#6]
`Type:` Script bug

`Description:` At the end of Marsus' speech explaining the two options for getting the player into the mine, the mod attempts to perform an auto save but saving is blocked by the scene

`Version:` Probably all versions after v1.0

`Steps to repro:` Ask Marsus about his ideas for getting into the mine, while the auto save feature in the MCM is active

`Cause:` The `setinchargen` save-block is active when a `save` call is made

`Suggested fix:` Delay the attempt to save until after the scene ends

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.5
