### ISSUE TITLE
Exiting conversation with Vilgen breaks main quest

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#7]
`Type:` Oversight

`Description:` After giving Vilgen the special ale, if you exit the conversation before it finishes, the quest stage will not progress and the option to hear about Runa does not appear, soft-locking the quest

`Version:` Versions after v1.0

`Steps to repro:` Give Vilgen the special ale, and during his explanation about Runa press tab (or exit the conversation some other way) then try to speak to Vilgen again.

`Cause:` There is no option to resume Vilgen's explanation (like there is with Lod)

`Suggested fix:` Add a walkaway dialog or an additional dialogue branch that continues the conversation if the ale was given to Vilgen.  (Or, to mimic the "Skip" options, provide the possibility of having sex with him after giving him the ale)

**Comment by DogmaMods** [comment]
Fixed in 1.2.0.7
