### ISSUE TITLE
Achievement ExAch17 does not exist

### ISSUE THREAD

**Issue by brewmasterhal** [DogmaMods/thief#9]
`Type:` Inaccessible Achievement

`Description:` The secret achievement ExAch17 is never awarded by any script

`Version:` All versions

`Steps to repro:` None

`Cause:` Call to `SetAchievementUltraDone(17)` is not present in any script

`Suggested fix:` Unclear where it is intended to be awarded: text is "Страсть" / "Passion"

**Comment by DogmaMods** [comment]
ID reassigned for another achievement
